/// Flutter icons SecRC
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SecRC
///      fonts:
///       - asset: fonts/SecRC.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SecRC {
  SecRC._();

  static const _kFontFam = 'SecRC';
  static const String? _kFontPkg = null;

  static const IconData hrv =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bypass =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sev =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
